CREATE TABLE DANHMUC(
	ID CHAR(4) PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL
);

CREATE TABLE THEHE(
	ID CHAR(5) PRIMARY KEY,
	NAME NVARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE SANPHAM(
	ID CHAR(5) PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	SIZE VARCHAR(15) NOT NULL,
	SCREEN VARCHAR(20) NOT NULL,
	CPU VARCHAR(15) NOT NULL,
	RAM VARCHAR(15) NOT NULL,
	ID_DANHMUC CHAR(4) FOREIGN KEY REFERENCES DANHMUC(ID),
	ID_THEHE CHAR(5) FOREIGN KEY REFERENCES THEHE(ID)
)

CREATE TABLE BONHOTRONG(
	ID VARCHAR(5) PRIMARY KEY,
	NAME VARCHAR NOT NULL
)

CREATE TABLE BANGIA(
	ID_SANPHAM CHAR(5) FOREIGN KEY REFERENCES SANPHAM(ID),
	ID_BONHOTRONG VARCHAR(5) FOREIGN KEY REFERENCES BONHOTRONG(ID),
	NGAYAPDUNG DATE NOT NULL,
	GIATIEN MONEY NOT NULL
)

CREATE TABLE SOLUONG(
	ID_SANPHAM CHAR(5) FOREIGN KEY REFERENCES SANPHAM(ID),
	ID_BONHOTRONG VARCHAR(5) FOREIGN KEY REFERENCES BONHOTRONG(ID),
	SOLUONG INT NOT NULL
)

CREATE TABLE HINHANH(
	SRC VARCHAR(100) PRIMARY KEY,
	ID_SANPHAM CHAR(5) FOREIGN KEY REFERENCES SANPHAM(ID)
)