CREATE DATABASE APPLERESELLER;
USE APPLERESELLER;

CREATE TABLE DANHMUC(
	ID CHAR(4) PRIMARY KEY,
	NAME VARCHAR(10) NOT NULL
);

CREATE TABLE THEHE(
	ID CHAR(5) PRIMARY KEY,
	NAME NVARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE SANPHAM(
	ID CHAR(5) PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	SIZE VARCHAR(15) NOT NULL,
	SCREEN VARCHAR(20) NOT NULL,
	CPU VARCHAR(15) NOT NULL,
	RAM VARCHAR(15) NOT NULL,
	ID_DANHMUC CHAR(4) FOREIGN KEY REFERENCES DANHMUC(ID),
	ID_THEHE CHAR(5) FOREIGN KEY REFERENCES THEHE(ID)
)

CREATE TABLE BONHOTRONG(
	ID VARCHAR(5) PRIMARY KEY,
	NAME VARCHAR NOT NULL
)

CREATE TABLE BANGIA(
	ID_SANPHAM CHAR(5) FOREIGN KEY REFERENCES SANPHAM(ID),
	ID_BONHOTRONG VARCHAR(5) FOREIGN KEY REFERENCES BONHOTRONG(ID),
	NGAYAPDUNG DATE NOT NULL,
	GIATIEN MONEY NOT NULL,
	CONSTRAINT PK_BANGIA PRIMARY KEY (ID_SANPHAM, ID_BONHOTRONG, NGAYAPDUNG)
)

CREATE TABLE SOLUONG(
	ID_SANPHAM CHAR(5) FOREIGN KEY REFERENCES SANPHAM(ID),
	ID_BONHOTRONG VARCHAR(5) FOREIGN KEY REFERENCES BONHOTRONG(ID),
	SOLUONG INT NOT NULL,
	CONSTRAINT PK_SOLUONG PRIMARY KEY (ID_SANPHAM,ID_BONHOTRONG)
)

CREATE TABLE HINHANH(
	SRC VARCHAR(100) PRIMARY KEY,
	ID_SANPHAM CHAR(5) FOREIGN KEY REFERENCES SANPHAM(ID)
)

CREATE TABLE LOAITAIKHOAN(
	ID CHAR(3) PRIMARY KEY,
	NAME NVARCHAR(10) NOT NULL
)

CREATE TABLE TAIKHOAN(
	USERNAME VARCHAR(20) PRIMARY KEY,
	PASSWORD CHAR(64) NOT NULL,
	TYPE CHAR(3) NOT NULL FOREIGN KEY REFERENCES LOAITAIKHOAN(ID)
)

CREATE TABLE KHACHHANG(
	ID CHAR(5) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	PHONE CHAR(10) NOT NULL,
	BIRTH DATE NOT NULL,
	GENDER BIT NOT NULL,
	CCID VARCHAR(15) NOT NULL,
	ADDRESS NVARCHAR(50) NOT NULL,
	USERNAME VARCHAR(20) FOREIGN KEY REFERENCES TAIKHOAN(USERNAME)
)

CREATE TABLE GIOHANG(
	ID CHAR(5) PRIMARY KEY,
	ID_KHACHHANG CHAR(5) FOREIGN KEY REFERENCES KHACHHANG(ID)
)

CREATE TABLE CHITIETGH(
	ID_GIOHANG CHAR(5) NOT NULL FOREIGN KEY REFERENCES GIOHANG(ID),
	ID_SANPHAM CHAR(5) NOT NULL FOREIGN KEY REFERENCES SANPHAM(ID),
	ID_BONHOTRONG VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES BONHOTRONG(ID),
	SOLUONG INT NOT NULL CHECK(SOLUONG > 0),
	THANHTIEN MONEY NOT NULL,
	CONSTRAINT PK_CHTIETGH PRIMARY KEY (ID_GIOHANG,ID_SANPHAM,ID_BONHOTRONG)
)

CREATE TABLE NHANVIEN(
	ID CHAR(5) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	PHONE CHAR(10) NOT NULL,
	BIRTH DATE NOT NULL,
	GENDER BIT NOT NULL,
	CCID VARCHAR(15) NOT NULL,
	ADDRESS NVARCHAR(50) NOT NULL,
	USERNAME VARCHAR(20) FOREIGN KEY REFERENCES TAIKHOAN(USERNAME)
)

CREATE TABLE DIACHIGIAOHANG(
	ID CHAR(5) PRIMARY KEY,
	ID_KHACHHANG CHAR(5) FOREIGN KEY REFERENCES KHACHHANG(ID),
	ADDRESS NVARCHAR(50) NOT NULL
)

CREATE TABLE HOADON(
	ID CHAR(6) PRIMARY KEY,
	ID_GIOHANG CHAR(5) FOREIGN KEY REFERENCES GIOHANG(ID),
	ID_DIACHIGIAOHANG CHAR(5) FOREIGN KEY REFERENCES DIACHIGIAOHANG(ID),
	TOTAL MONEY NOT NULL,
	ID_NHANVIEN CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(ID)
)